### ISSUE TITLE
Cannot import the module

### ISSUE THREAD

**Issue by K0HAX** [adamsherman/pytrademonster#2]
I cannot import the module using the documentation provided. I get the following error.

```
Python 3.4.3 (default, Jan  5 2016, 06:34:07) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytrademonster import PyTradeMonster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/dev/pytrademonster/pytrademonster/__init__.py", line 3, in <module>
    from pyTradeMonster import PyTradeMonster, log
ImportError: No module named 'pyTradeMonster'
>>> 
```

**Comment by adamsherman** [comment]
Did you run the setup.py? Also, its tested against python 2.7 as per the
readme.

**Comment by K0HAX** [comment]
Ok, that was the problem I had. I was using Python3. I switched to 2.7 and now it loads, but I still can't get a quote.

This is my error.

```
>>> symbolDict = {'SPY' : TradeMonsterConstants.INSTRUMENTS.EQUITY}
>>> quoteResult = quotesService.getParsedQuotes(symbolDict)                                                                                                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytrademonster/services/quotesService.py", line 127, in getParsedQuotes
    quote.symbol = item['symbol']
TypeError: string indices must be integers
>>> 
```

**Comment by K0HAX** [comment]
Nevermind, I built from the git tree and it worked. The version that got installed via "pip install" was old.
