### ISSUE TITLE
positionService.getParsedPositionsDetail gives an error

### ISSUE THREAD

**Issue by K0HAX** [adamsherman/pytrademonster#3]
I'm making progress getting this library to work, but I ran into an error when trying to get my positions from it.

```
>>> positions = positionService.getParsedPositionsDetail(accounts[ACCOUNT_NUMBER].accountId)                                                                                                               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 103, in getParsedPositionsDetail
    self.parseSinglePositionQuote(position, Position)
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 126, in parseSinglePositionQuote
    position.accountId = xmlPosition['accountId']
TypeError: string indices must be integers
>>> 
```

**Comment by adamsherman** [comment]
There was an issue handling spreads. Try now.

**Comment by K0HAX** [comment]
It's a little different now. I'm getting a KeyError. This might be because I'm checking on a day when the market is closed though.

```
>>> positions = positionService.getParsedPositionsDetail(accounts[ACCOUNT_NUMBER].accountId)                                                                                                                                                                                   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 95, in getParsedPositionsDetail
    self.parsePosition(Position,item,positions)
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 108, in parsePosition
    position = self.createPositionItemObject(item, Position)
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 126, in createPositionItemObject
    self.parseSinglePositionQuote(position, positionLeg)
  File "/usr/lib/python2.7/site-packages/pytrademonster-0.12-py2.7.egg/pytrademonster/services/positionService.py", line 139, in parseSinglePositionQuote
    position.day = xmlPosition['day']
KeyError: 'day'
>>> 
```

**Comment by adamsherman** [comment]
Unfortunately, I cannot replicate this as it might be unique to the response to whatever position you have on. I added some checks around parsing, as you can see, but feel free to add more as there is no guarantee on the response message they send based on position type - i.e spread, single leg etc...
